package com.moti.datesserver.entities;

import com.moti.datesserver.enums.*;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "users")
public class UserEntity {
    @Id
    @GeneratedValue
    //Generated by DB
    private long id;
    //User name for login
    @Column(name = "user_name", nullable = false, unique = true)
    private String userName;
    //Will not be presented
    @Enumerated(EnumType.STRING)
    @Column(name = "user_type", nullable = false)
    private UserType userType;
    //for loginh
    @Column(name = "password", nullable = false)
    private String password;
    //Main phone number
    @Column(name = "phone_number", nullable = false)
    private String poneNumber;
    //Gender
    @Column(name = "gender", nullable = false)
    private Gender gender;
    @Column(name = "status", nullable = false)
    private Status status;
    @Column(name="first_Name",nullable = false)
    private String firstName;
    @Column(name="last_Name",nullable = false)
    private String lastName;
    //Date of birth - validation?
    @Column(name="date_of_birth",nullable = false)
    private Date dateOfBirth;
    //Open text about myself
    @Column(name="information_About_Myself" ,nullable = false)
    private String informationAboutMyself;
    //Open search
    @Column(name="i_am_looking_for" ,nullable = false)
    private Gender  lookingFor;
    @Column(name="introduction_purpose",nullable = false)
    private MeetingPurpose introductionPurpose;

    public UserEntity(long id, String userName, String password, String poneNumber, Gender gender, Status status, String firstName, String lastName, Date dateOfBirth, String informationAboutMyself, Gender lookingFor, MeetingPurpose introductionPurpose) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.poneNumber = poneNumber;
        this.gender = gender;
        this.status = status;
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.informationAboutMyself = informationAboutMyself;
        this.lookingFor = lookingFor;
        this.introductionPurpose = introductionPurpose;
    }

    public UserEntity() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public UserType getUserType() {
        return userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPoneNumber() {
        return poneNumber;
    }

    public void setPoneNumber(String poneNumber) {
        this.poneNumber = poneNumber;
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getInformationAboutMyself() {
        return informationAboutMyself;
    }

    public void setInformationAboutMyself(String informationAboutMyself) {
        this.informationAboutMyself = informationAboutMyself;
    }

    public Gender getLookingFor() {
        return lookingFor;
    }

    public void setLookingFor(Gender lookingFor) {
        this.lookingFor = lookingFor;
    }

    public MeetingPurpose getIntroductionPurpose() {
        return introductionPurpose;
    }

    public void setIntroductionPurpose(MeetingPurpose introductionPurpose) {
        this.introductionPurpose = introductionPurpose;
    }
}

